# Generated by Django 2.0.13 on 2020-08-21 17:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='assign_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='call',
            name='end_date',
        ),
        migrations.AddField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 19, 51, 36, 524059)),
        ),
        migrations.AddField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 1, 51, 36, 524059), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AddField(
            model_name='call',
            name='is_assigned',
            field=models.BooleanField(default=False, verbose_name='indicate wheather call has engineer or not'),
        ),
        migrations.AddField(
            model_name='call',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 19, 51, 36, 524059), null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('pending', 'Pending'), ('completed', 'Completed')], default='unassigned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='call',
            name='notification_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='machine',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='customer.Customer'),
        ),
    ]
