# Generated by Django 2.0.13 on 2020-08-01 18:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 2, 2, 26, 6, 646672), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
