# Generated by Django 2.0.13 on 2020-08-21 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20200821_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='created_date',
            new_name='assign_date',
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 19, 53, 43, 736724)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 1, 53, 43, 736724), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 19, 53, 43, 736724), null=True),
        ),
    ]
