# Generated by Django 2.0.13 on 2020-08-03 23:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0007_auto_20200804_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 4, 7, 16, 8, 375738), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='customer.Customer'),
        ),
    ]
