# Generated by Django 2.0.13 on 2020-08-06 17:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_auto_20200804_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='assigned',
            field=models.BooleanField(default=False, verbose_name='indicate wheather call has engineer or not'),
        ),
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 1, 54, 47, 888855), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
