# Generated by Django 2.0.13 on 2020-08-06 19:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0011_auto_20200806_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('unassigned', 'Unassigned'), ('pending', 'Pending'), ('completed', 'Completed')], default='unassigned', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 3, 10, 26, 355010), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
