# Generated by Django 2.0.13 on 2020-08-07 12:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0015_auto_20200806_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 20, 53, 44, 914040), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
