# Generated by Django 2.0.13 on 2020-08-17 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0016_auto_20200807_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 3, 19, 30, 487622), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
