# Generated by Django 2.0.13 on 2020-08-17 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0017_auto_20200817_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 3, 24, 21, 786220), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
