# Generated by Django 2.0.13 on 2020-08-18 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0018_auto_20200817_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='assign_date',
            new_name='created_date',
        ),
        migrations.RemoveField(
            model_name='call',
            name='end_date',
        ),
    ]
