# Generated by Django 2.0.13 on 2020-08-18 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0019_auto_20200819_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 1, 6, 4, 669478)),
        ),
        migrations.AddField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 7, 6, 4, 669478), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
