# Generated by Django 2.0.13 on 2020-08-21 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0020_auto_20200819_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='response_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 19, 32, 45, 766294)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 1, 32, 45, 766294), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
