# Generated by Django 2.0.13 on 2020-08-21 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0023_auto_20200821_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='response_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 19, 48, 23, 152194), null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 21, 19, 48, 23, 152194)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 22, 1, 48, 23, 152194), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
