# Generated by Django 2.0.13 on 2020-08-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('engineer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='engineer.Area', to_field='slug'),
        ),
        migrations.AddField(
            model_name='customer',
            name='engineers',
            field=models.ManyToManyField(blank=True, related_name='customers', to='engineer.Engineer'),
        ),
    ]
