# Generated by Django 2.0.13 on 2020-08-03 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, help_text='donot fill this it will be filled automatically', unique=True),
        ),
    ]
