# Generated by Django 2.2.15 on 2020-08-28 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20200828_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='begin_at',
            field=models.TimeField(default=datetime.datetime(2020, 8, 28, 15, 37, 49, 334442)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='finish_at',
            field=models.TimeField(default=datetime.datetime(2020, 8, 28, 23, 37, 49, 334442)),
        ),
    ]
