# Generated by Django 2.2.15 on 2020-08-28 17:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20200828_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='begin_at',
            field=models.TimeField(default=datetime.datetime(2020, 8, 28, 19, 35, 52, 491307)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='finish_at',
            field=models.TimeField(default=datetime.datetime(2020, 8, 29, 3, 35, 52, 491307)),
        ),
    ]
