# Generated by Django 2.2.15 on 2020-09-10 22:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20200828_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='begin_at',
            field=models.TimeField(default=datetime.datetime(2020, 9, 11, 0, 20, 26, 627028)),
        ),
        migrations.AlterField(
            model_name='customer',
            name='finish_at',
            field=models.TimeField(default=datetime.datetime(2020, 9, 11, 8, 20, 26, 627028)),
        ),
    ]
