# Generated by Django 2.2.15 on 2020-10-03 12:09

import customer.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20200912_2202'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrganization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='donot fill this it will be filled automatically', unique=True)),
                ('name', models.CharField(max_length=50)),
                ('discription', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerBranch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='donot fill this it will be filled automatically', unique=True)),
                ('location', models.CharField(max_length=255, verbose_name='Address location')),
                ('address', models.URLField(verbose_name='address site')),
                ('telephone', models.PositiveIntegerField(blank=True, null=True, verbose_name='telephone')),
                ('begin_at', models.TimeField(default=datetime.time(8, 0))),
                ('finish_at', models.TimeField(default=datetime.time(16, 0))),
                ('branche_machines', models.PositiveIntegerField(default=customer.models.CustomerBranch.get_machine_number)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='customer.CustomerOrganization')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Mobile Number')),
                ('office_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Office Number')),
                ('cutomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_persons', to='customer.CustomerBranch')),
            ],
        ),
    ]
