# Generated by Django 2.2.15 on 2020-10-03 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_contactperson_customerbranch_customerorganization'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='customer.CustomerOrganization'),
        ),
    ]
