# Generated by Django 2.2.15 on 2020-10-03 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customer_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customerbranch',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='customerorganization',
            name='slug',
        ),
    ]
