# Generated by Django 2.2.15 on 2020-10-03 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20201003_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerbranch',
            name='branche_machines',
        ),
    ]
