# Generated by Django 2.2.15 on 2020-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_customerorganization_organization_machines_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='first_week_dayoff',
            field=models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'NoDayoff')], default=7),
        ),
        migrations.AddField(
            model_name='customer',
            name='second_week_dayoff',
            field=models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (7, 'NoDayoff')], default=7),
        ),
    ]
