# Generated by Django 2.2.15 on 2020-10-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_auto_20201013_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='area',
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='mobile_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Mobile Number'),
        ),
        migrations.AlterField(
            model_name='contactperson',
            name='office_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Office Number'),
        ),
    ]
