# Generated by Django 2.2.17 on 2020-11-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_auto_20201020_2136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='address',
            new_name='address_site',
        ),
        migrations.AlterField(
            model_name='department',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='customer.Customer'),
        ),
    ]
