# Generated by Django 2.2.17 on 2020-11-03 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_auto_20201104_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='organization',
        ),
    ]
