# Generated by Django 2.2.17 on 2020-11-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_auto_20201104_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='engineers',
            field=models.ManyToManyField(blank=True, related_name='customers', to='engineer.Engineer'),
        ),
    ]
