# Generated by Django 2.0.13 on 2020-08-21 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='area code')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('margin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="start with 'EGD20' and followed by your number", max_length=255, verbose_name='xerox username')),
                ('joining_date', models.DateField()),
                ('no_of_calls', models.PositiveIntegerField(default=0)),
                ('no_of_calls_pending', models.PositiveIntegerField(default=0)),
                ('no_ofcalls_success', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineer.Area')),
            ],
        ),
        migrations.CreateModel(
            name='EngineerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('published', 'published'), ('rejected', 'rejected')], max_length=50)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.Engineer')),
            ],
            options={
                'permissions': (('can_approve_or_reject_review', 'can approve or reject review'),),
            },
        ),
    ]
