# Generated by Django 2.1 on 2019-03-22 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='area code')),
                ('slug', models.SlugField(unique=True)),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('margin', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="start with 'EGD20' and followed by your number", max_length=255, verbose_name='xerox username')),
                ('joining_date', models.DateField()),
                ('no_of_calls', models.PositiveIntegerField(default=0)),
                ('no_of_calls_pending', models.PositiveIntegerField(default=0)),
                ('no_ofcalls_success', models.PositiveIntegerField(default=0)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineer.Area')),
                ('engineer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EngineerReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(null=True)),
                ('state', models.CharField(choices=[('pending', 'pending'), ('published', 'published'), ('rejected', 'rejected')], max_length=50)),
                ('auther', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.Engineer')),
            ],
            options={
                'permissions': (('can_approve_or_reject_review', 'can approve or reject review'),),
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.Engineer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='engineer_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.EngineerReview'),
        ),
    ]
