# Generated by Django 2.0.13 on 2020-08-21 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='engineer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.Engineer'),
        ),
        migrations.AddField(
            model_name='comment',
            name='engineer_review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineer.EngineerReview'),
        ),
    ]
