# Generated by Django 2.0.13 on 2020-08-03 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engineer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='engineer',
        ),
        migrations.AddField(
            model_name='engineer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='engineer', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
