# Generated by Django 2.0.13 on 2020-08-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_auto_20200803_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
