# Generated by Django 2.2.15 on 2020-09-10 22:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_auto_20200821_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
