# Generated by Django 2.2.15 on 2020-09-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0003_auto_20200911_0020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineerreview',
            name='auther',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='EngineerReview',
        ),
    ]
