# Generated by Django 2.2.15 on 2020-10-03 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0004_auto_20200919_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='no_of_calls_dispatched',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
