# Generated by Django 2.2.15 on 2020-10-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0006_auto_20201009_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='first_week_dayoff',
            field=models.IntegerField(choices=[(2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (0, 'Saturday'), (1, 'Sunday'), (7, 'NoDayoff')], default=0),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='second_week_dayoff',
            field=models.IntegerField(choices=[(2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday'), (0, 'Saturday'), (1, 'Sunday'), (7, 'NoDayoff')], default=6),
        ),
    ]
