# Generated by Django 2.2.15 on 2020-10-20 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0007_auto_20201013_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='slug',
        ),
    ]
