# Generated by Django 2.2.17 on 2020-12-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0008_remove_area_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='engineers', to='engineer.Area'),
        ),
    ]
