# Generated by Django 2.2.18 on 2021-02-13 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210213_1214'),
        ('engineer', '0010_notificationtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NotificationToken',
        ),
    ]
