# Generated by Django 2.2.19 on 2021-02-24 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0011_delete_notificationtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engineer',
            name='no_of_calls',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='no_of_calls_dispatched',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='no_of_calls_pending',
        ),
        migrations.RemoveField(
            model_name='engineer',
            name='no_ofcalls_success',
        ),
    ]
