# Generated by Django 2.0.13 on 2020-08-03 10:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20200801_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 3, 18, 46, 31, 315773), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
