# Generated by Django 2.2.15 on 2020-08-28 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0002_auto_20200824_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='response_time',
        ),
        migrations.AddField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 13, 44, 49, 109644), null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 13, 44, 49, 109644)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 19, 44, 49, 109644), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
