# Generated by Django 2.2.15 on 2020-08-28 13:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import machine.models


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0002_auto_20200821_2019'),
        ('machine', '0003_auto_20200828_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 15, 37, 49, 339442)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 21, 37, 49, 339442), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 15, 37, 49, 339442), null=True),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(default='', max_length=50)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='machine.Call')),
                ('engineer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='engineer.Engineer')),
            ],
        ),
    ]
