# Generated by Django 2.2.15 on 2020-08-28 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0004_auto_20200828_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 15, 41, 40, 970372)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 21, 41, 40, 970372), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 15, 41, 40, 970372), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='customer_name',
            field=models.CharField(default='',max_length=50),
        ),
    ]
