# Generated by Django 2.2.15 on 2020-08-28 14:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0006_auto_20200828_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='notes_for_dispatcher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 16, 42, 20, 71106)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 22, 42, 20, 71106), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 28, 16, 42, 20, 71106), null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('pending', 'Pending'), ('completed', 'Completed')], default='unassigned', max_length=20, verbose_name='Status'),
        ),
    ]
