# Generated by Django 2.2.15 on 2020-09-12 20:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0009_auto_20200911_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 22, 2, 17, 689900)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 4, 2, 17, 689900), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 22, 2, 17, 689900), null=True),
        ),
    ]
