# Generated by Django 2.2.15 on 2020-09-13 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0010_auto_20200912_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 13, 21, 30, 50, 395908)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 14, 3, 30, 50, 395908), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 13, 21, 30, 50, 395908), null=True),
        ),
    ]
