# Generated by Django 2.2.15 on 2020-09-19 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0012_auto_20200919_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineerreview',
            name='file_data',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='engineerreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 19, 20, 55, 36, 313217)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 20, 2, 55, 36, 313217), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 19, 20, 55, 36, 313217), null=True),
        ),
    ]
