# Generated by Django 2.0.13 on 2020-08-06 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0012_auto_20200806_2110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='assigned',
            new_name='is_assigned',
        ),
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 3, 13, 28, 952920), help_text='the default value is 6 hours + assign_date'),
        ),
    ]
