# Generated by Django 2.0.13 on 2020-08-06 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0013_auto_20200806_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 7, 3, 24, 15, 817883), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='notification_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
