# Generated by Django 2.2.15 on 2020-09-22 20:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0013_auto_20200919_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='previous_state',
            field=models.CharField(blank=True, help_text='do not fill this anywhere', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 22, 22, 9, 50, 150959)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 4, 9, 50, 150959), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 22, 22, 9, 50, 150959), null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/reports/'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_copy',
            field=models.FileField(blank=True, null=True, upload_to='files/reports/'),
        ),
    ]
