# Generated by Django 2.2.15 on 2020-09-23 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0014_auto_20200922_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerreview',
            old_name='auther',
            new_name='engineer',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='machine',
        ),
        migrations.AddField(
            model_name='machine',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='machine.Contract'),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 21, 17, 28, 296928)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 3, 17, 28, 296928), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 21, 17, 28, 296928), null=True),
        ),
    ]
