# Generated by Django 2.2.15 on 2020-09-23 19:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0015_auto_20200923_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='engineerreview',
            old_name='review',
            new_name='review_content',
        ),
        migrations.AddField(
            model_name='engineerreview',
            name='review_title',
            field=models.CharField(default='hello', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 21, 43, 28, 609226)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 3, 43, 28, 609226), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 21, 43, 28, 609226), null=True),
        ),
        migrations.AlterField(
            model_name='engineerreview',
            name='engineer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='engineer.Engineer'),
        ),
        migrations.CreateModel(
            name='ImageReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Image name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='machine.EngineerReview')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Image name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='machine.Report')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FileReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='machine.EngineerReview')),
            ],
        ),
        migrations.CreateModel(
            name='FileReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Image name')),
                ('file1', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='machine.Report')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
