# Generated by Django 2.2.15 on 2020-09-23 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0016_auto_20200923_2145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='call',
            old_name='previous_state',
            new_name='previous_status',
        ),
        migrations.RenameField(
            model_name='engineerreview',
            old_name='state',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='engineerreview',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='engineerreview',
            name='image',
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 23, 21, 55, 35, 843247)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 3, 55, 35, 843247), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 23, 21, 55, 35, 843247), null=True),
        ),
    ]
