# Generated by Django 2.2.15 on 2020-09-28 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
import machine.models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0018_auto_20200923_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_category',
            field=models.CharField(blank=True, choices=[('mono workcentre', 'B/W workcentre'), ('color workcentre', 'Color workcentre'), ('mono phasor', 'B/W phasor'), ('color phasor', 'Color phasor'), ('wide format', 'Wide Format')], max_length=100, null=True, verbose_name='Machine Category'),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 28, 20, 10, 0, 942501)),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 2, 10, 0, 942501), help_text='the default value is 6 hours + assign_date'),
        ),
        migrations.AlterField(
            model_name='call',
            name='response_time_end',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 28, 20, 10, 0, 942501), null=True),
        ),
        migrations.AlterField(
            model_name='engineerreview',
            name='file_data',
            field=models.FileField(blank=True, null=True, upload_to=machine.models.get_upload_name),
        ),
        migrations.AlterField(
            model_name='engineerreview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=machine.models.get_upload_name),
        ),
        migrations.AlterField(
            model_name='imagereport',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=machine.models.get_upload_name),
        ),
        migrations.AlterField(
            model_name='imagereview',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=machine.models.get_upload_name),
        ),
        migrations.AlterField(
            model_name='machine',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='machine.Category'),
        ),
    ]
