# Generated by Django 2.2.15 on 2020-09-29 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0019_auto_20200928_2010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='response_time_end',
        ),
        migrations.AddField(
            model_name='call',
            name='optimum_completed_date',
            field=models.DateTimeField(blank=True, help_text='the default value is 6 hours + assign_date', null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='response_time_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
