# Generated by Django 2.2.15 on 2020-09-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0020_auto_20200929_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='category',
        ),
        migrations.AddField(
            model_name='call',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('dispatched', 'Dispatched'), ('pending', 'Pending'), ('completed', 'Completed')], default='unassigned', max_length=20, verbose_name='Status'),
        ),
    ]
