# Generated by Django 2.2.15 on 2020-10-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0021_auto_20200930_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='real_assigned_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='real_completed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
