# Generated by Django 2.2.15 on 2020-10-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0022_auto_20201009_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_points',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_response_time',
            field=models.IntegerField(blank=True, choices=[(4, 'Production'), (6, 'Office'), (6, 'Radiology')], null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_return_time',
            field=models.IntegerField(blank=True, choices=[(4, 'Production'), (7, 'Office'), (7, 'Radiology')], null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='speed',
            field=models.IntegerField(blank=True, choices=[(10, 10), (15, 15), (20, 20), (25, 25), (30, 30), (35, 35), (45, 45), (55, 55), (65, 65), (75, 75), (90, 90)], null=True),
        ),
    ]
