# Generated by Django 2.2.15 on 2020-10-09 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0023_auto_20201009_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='end_of_contarct',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contract',
            name='monthly_fees',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='monthly fees'),
        ),
        migrations.AddField(
            model_name='contract',
            name='start_of_contract',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('FSMA', 'FSMA'), ('Time', 'Time'), ('LIS', 'LIS'), ('FM', 'FM'), ('XPPS', 'XPPS'), ('T&M', 'T&M')], max_length=50, null=True),
        ),
    ]
