# Generated by Django 2.2.15 on 2020-10-09 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0024_auto_20201009_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='contract',
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_of_contarct',
            field=models.DateTimeField(blank=True, help_text='do not fill this field it will add a year automatically', null=True),
        ),
    ]
