# Generated by Django 2.2.15 on 2020-10-09 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0025_auto_20201009_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machine', to='machine.Contract'),
        ),
    ]
