# Generated by Django 2.2.15 on 2020-10-09 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0026_machine_contract'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='machine_serial',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
