# Generated by Django 2.2.15 on 2020-10-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0027_contract_machine_serial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='end_of_contarct',
            new_name='end_of_contract',
        ),
        migrations.AlterField(
            model_name='machine',
            name='contract',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='machine', to='machine.Contract'),
        ),
    ]
