# Generated by Django 2.2.15 on 2020-10-13 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0028_auto_20201010_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='fault',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('mobile', models.PositiveIntegerField()),
                ('telephone', models.PositiveIntegerField(blank=True, null=True)),
                ('email_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='call_contacts', to='machine.Call')),
            ],
        ),
    ]
