# Generated by Django 2.2.15 on 2020-10-16 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0030_auto_20201016_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='notes_from_customer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
