# Generated by Django 2.2.15 on 2020-10-18 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engineer', '0007_auto_20201013_2228'),
        ('machine', '0032_machine_model_of_machine'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='previous_engineer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='previous_engineer_calls', to='engineer.Engineer'),
        ),
    ]
