# Generated by Django 2.2.15 on 2020-10-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0033_call_previous_engineer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='name',
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_response_time',
            field=models.IntegerField(blank=True, choices=[(4, 'Production'), (6, 'Workcentre'), (9, 'Phasor'), (6, 'Radiology')], null=True),
        ),
    ]
