# Generated by Django 2.2.15 on 2020-10-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0034_auto_20201019_1959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='machine_model',
        ),
    ]
