# Generated by Django 2.2.15 on 2020-10-19 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0035_remove_machine_machine_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='slug',
        ),
    ]
