# Generated by Django 2.2.15 on 2020-10-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0036_remove_machine_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='installation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial2',
            field=models.CharField(blank=True, help_text='fill this if your serial consists of numbers and letters', max_length=10, null=True, unique=True, verbose_name='non-standard serial'),
        ),
    ]
