# Generated by Django 2.2.15 on 2020-10-19 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0037_auto_20201019_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='model_of_machine',
            new_name='machine_model',
        ),
    ]
