# Generated by Django 2.2.15 on 2020-10-20 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0038_auto_20201019_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='machine_return_time',
            new_name='machine_callback_time',
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('FSMA', 'FSMA'), ('Time', 'Time'), ('LIS', 'LIS'), ('FM', 'FM'), ('XPPS', 'XPPS'), ('T&M', 'T&M'), ('Warranty', 'Warranty')], max_length=50, null=True),
        ),
    ]
