# Generated by Django 2.2.15 on 2020-10-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0039_auto_20201020_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('dispatched', 'Dispatched'), ('incomplete', 'Incomplete'), ('completed', 'Completed')], default='unassigned', max_length=20, verbose_name='Status'),
        ),
    ]
