# Generated by Django 2.2.15 on 2020-10-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0040_auto_20201020_2038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='report',
            name='machine_serial',
        ),
        migrations.RemoveField(
            model_name='report',
            name='notification_number',
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('completed', 'Completed')], default='incomplete', max_length=50),
        ),
    ]
