# Generated by Django 2.2.15 on 2020-10-20 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0041_auto_20201020_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='engineers',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='speed',
        ),
    ]
