# Generated by Django 2.2.15 on 2020-10-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0042_auto_20201020_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_callback_time',
            field=models.IntegerField(blank=True, choices=[(4, 'Production'), (7, 'Office/radiology')], null=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_category',
            field=models.CharField(blank=True, choices=[('mono workcentre', 'B/W workcentre'), ('color workcentre', 'Color workcentre'), ('mono phasor', 'B/W phasor'), ('color phasor', 'Color phasor'), ('wide format', 'Wide Format'), ('mono production', 'B/W production'), ('color production', 'Color production'), ('radiology', 'Radiology')], max_length=100, null=True, verbose_name='Machine Category'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='machine_response_time',
            field=models.IntegerField(blank=True, choices=[(4, 'Production'), (6, 'Workcentre/radiology'), (9, 'Phasor')], null=True),
        ),
    ]
