# Generated by Django 2.2.17 on 2020-11-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0043_auto_20201024_2221'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machine',
            old_name='description',
            new_name='machine_location',
        ),
    ]
