# Generated by Django 2.2.17 on 2020-11-03 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0045_auto_20201104_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='begin_at',
            field=models.TimeField(default=datetime.time(8, 0)),
        ),
        migrations.AddField(
            model_name='machine',
            name='finish_at',
            field=models.TimeField(default=datetime.time(16, 0)),
        ),
        migrations.AddField(
            model_name='machine',
            name='first_week_dayoff',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'NoDayoff')], default=7),
        ),
        migrations.AddField(
            model_name='machine',
            name='second_week_dayoff',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday'), (7, 'NoDayoff')], default=7),
        ),
    ]
