# Generated by Django 2.2.17 on 2020-11-05 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0046_auto_20201104_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_contacts', to='machine.Call'),
        ),
    ]
