# Generated by Django 2.2.17 on 2020-12-05 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0048_auto_20201114_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='serial',
            field=models.BigIntegerField(blank=True, help_text='fill this if your serial is numbers only', unique=True, verbose_name='standard seial'),
        ),
    ]
