# Generated by Django 2.2.17 on 2021-01-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0050_auto_20201215_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='finishs_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),

    ]
