# Generated by Django 2.2.17 on 2021-01-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0051_auto_20210122_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='billing_meter1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='billing_meter2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='billing_meter_black',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='billing_meter_color',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='billing_meter_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
