# Generated by Django 2.2.17 on 2021-01-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0052_auto_20210122_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='callback_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='first_time_finish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='start_of_call',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
