# Generated by Django 2.2.17 on 2021-01-23 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0053_auto_20210123_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='delayed_call',
            field=models.BooleanField(default=False),
        ),
    ]
