# Generated by Django 2.2.17 on 2021-01-24 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0054_call_delayed_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='no_of_visits',
            field=models.IntegerField(default=0),
        ),
    ]
