# Generated by Django 2.2.17 on 2021-01-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0055_call_no_of_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='response_success_call',
            field=models.BooleanField(default=False),
        ),
    ]
