# Generated by Django 2.2.17 on 2021-02-01 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0056_call_response_success_call'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
