# Generated by Django 2.2.17 on 2021-02-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0057_auto_20210202_0038'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='down_success_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='down_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='response_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
