# Generated by Django 2.2.17 on 2021-02-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0058_auto_20210206_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='down_time_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='response_tail_success_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='call',
            name='response_time_tail_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
