# Generated by Django 4.1.1 on 2022-10-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0059_auto_20210206_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='machine_full_serial',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_serial',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
