# Generated by Django 2.2.15 on 2020-10-03 12:51

import customer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20201003_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerbranch',
            old_name='branche_machines',
            new_name='branche_machines_number',
        ),
        migrations.AddField(
            model_name='customerorganization',
            name='branche_machines_number',
            field=models.PositiveIntegerField(default=customer.models.CustomerOrganization.get_machine_number),
        ),
    ]
